//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaffManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DepartmentTb
    {
        public int DepartmentTbId { get; set; }
        [Display(Name ="Department Name")]
        public string DeparmentTbName { get; set; }
        [Display(Name = "Department Description")]
        public string departmentTbDescription { get; set; }
        [Display(Name ="Created By")]
        public string createdBy { get; set; }
        [Display(Name = "Created On")]
        public Nullable<System.DateTime> CreatedOn { get; set; }
        [Display(Name = "Updated BY")]
        public string UpdatedBy { get; set; }
        [Display(Name = "Updated On")]
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    }
}
