//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaffManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class RolesTb
    {
        public int RolesTbId { get; set; }
        [Display(Name="Role Name")]
        public string RoleTbName { get; set; }
        [Display(Name = "Role Description")]
        public string RoleTbDescription { get; set; }
        [Display(Name ="Created By")]
        public string CreatedBy { get; set; }
        [Display(Name = "Created On")]
        public System.DateTime CreatedOn { get; set; }
        [Display(Name = "Updated By")]
        public string UpdatedBy { get; set; }
        [Display(Name = "Updated On")]
        public System.DateTime UpdatedOn { get; set; }
    }
}
